[0m14:41:41.173702 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f443aec5550>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f443af09c50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f443af198d0>]}


============================== 14:41:41.175496 | 7af3886f-8d3b-4668-a8f8-c430c93a3824 ==============================
[0m14:41:41.175496 [info ] [MainThread]: Running with dbt=1.8.2
[0m14:41:41.176388 [debug] [MainThread]: running dbt with arguments {'use_colors': 'True', 'profiles_dir': '/home/ahona/.dbt', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'no_print': 'None', 'log_path': 'logs', 'quiet': 'False', 'printer_width': '80', 'warn_error': 'None', 'send_anonymous_usage_stats': 'True', 'introspect': 'True', 'write_json': 'True', 'debug': 'False', 'use_experimental_parser': 'False', 'indirect_selection': 'eager', 'partial_parse': 'True', 'invocation_command': 'dbt init', 'target_path': 'None', 'log_format': 'default', 'cache_selected_only': 'False', 'version_check': 'True', 'fail_fast': 'False', 'log_cache_events': 'False', 'static_parser': 'True'}
[0m14:41:41.203934 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse dict {'dir': PosixPath('/home/ahona/.dbt')}
[0m14:41:41.204588 [info ] [MainThread]: Creating dbt configuration folder at 
[0m14:41:52.015650 [debug] [MainThread]: Starter project path: /home/ahona/anaconda3/lib/python3.11/site-packages/dbt/include/starter_project
[0m14:41:52.024400 [info ] [MainThread]: 
Your new dbt project "covid_nineteen" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m14:41:52.025118 [info ] [MainThread]: Setting up your profile.
[0m14:43:08.593176 [info ] [MainThread]: Profile covid_nineteen written to /home/ahona/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m14:43:08.594662 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 87.50324, "process_user_time": 1.245316, "process_kernel_time": 0.16193, "process_mem_max_rss": "96104", "process_in_blocks": "49920", "process_out_blocks": "80"}
[0m14:43:08.595425 [debug] [MainThread]: Command `dbt init` succeeded at 14:43:08.595277 after 87.50 seconds
[0m14:43:08.595939 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f443bb1c410>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f443af19e10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f443f0a5d50>]}
[0m14:43:08.596447 [debug] [MainThread]: Flushing usage events
[0m14:43:18.608992 [debug] [MainThread]: Error sending anonymous usage statistics. Disabling tracking for this execution. If you wish to permanently disable tracking, see: https://docs.getdbt.com/reference/global-configs#send-anonymous-usage-stats.
[0m12:54:25.169352 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff12038d310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff12038ef10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff1203acbd0>]}


============================== 12:54:25.172278 | 6ee83010-db98-4b3a-b1e5-297a852afca4 ==============================
[0m12:54:25.172278 [info ] [MainThread]: Running with dbt=1.8.2
[0m12:54:25.173412 [debug] [MainThread]: running dbt with arguments {'introspect': 'True', 'printer_width': '80', 'static_parser': 'True', 'debug': 'False', 'write_json': 'True', 'cache_selected_only': 'False', 'log_path': 'logs', 'indirect_selection': 'eager', 'invocation_command': 'dbt run', 'version_check': 'True', 'profiles_dir': '/home/ahona/.dbt', 'send_anonymous_usage_stats': 'True', 'partial_parse': 'True', 'no_print': 'None', 'log_cache_events': 'False', 'use_experimental_parser': 'False', 'log_format': 'default', 'target_path': 'None', 'use_colors': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'quiet': 'False', 'warn_error': 'None', 'fail_fast': 'False'}
[0m12:54:25.174239 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/ahona/covid/analyticsengineering/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:54:25.175377 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.090616606, "process_user_time": 1.285824, "process_kernel_time": 0.099676, "process_mem_max_rss": "93656", "process_in_blocks": "8", "process_out_blocks": "16", "command_success": false}
[0m12:54:25.176037 [debug] [MainThread]: Command `dbt run` failed at 12:54:25.175896 after 0.09 seconds
[0m12:54:25.176542 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff1203ad250>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff12038e190>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff121c96910>]}
[0m12:54:25.177029 [debug] [MainThread]: Flushing usage events
